from constants import BATTLE_MODE_VEH_TAGS_EXCEPT_CLAN
from gui.prb_control.entities.base.pre_queue.vehicles_watcher import BaseVehiclesWatcher

class StrongholdVehiclesWatcher(BaseVehiclesWatcher):
    _BATTLE_MODE_VEHICLE_TAGS = BATTLE_MODE_VEH_TAGS_EXCEPT_CLAN