from shared_utils import CONST_CONTAINER

class FILTER_POPOVER_SECTION(CONST_CONTAINER):
    NATIONS, VEHICLE_TYPES, LEVELS, CUSTOMIZATION, SPECIALS, HIDDEN, PROGRESSIONS, TEXT_SEARCH, ROLES, ROLES_WITH_EXTRA = range(0, 10)