CMD_BATTLE_ROYALE_OPERATE_BRCOIN = 21003
CMD_BATTLE_ROYALE_OPERATE_STPCOIN = 21004
CMD_BATTLE_ROYALE_SET_RATING = 21005
BATTLE_ROYALE_REPAIR_COST = 10000

class Currency(object):
    BRCOIN = 'brcoin'
    STPCOIN = 'stpcoin'
    ALL = {
     BRCOIN, STPCOIN}