

class CUSTOMIZATION_CONSTS(object):
    HISTORICAL_TYPE = 0
    NON_HISTORICAL_TYPE = 1
    FANTASTICAL_TYPE = 2
    INNER_ENTRY_POINT_PROGRESSIVE = 'progressive'
    INNER_ENTRY_POINT_STATS_TRACKER = 'statsTracker'