

class SEASONS_CONSTANTS(object):
    SUMMER_INDEX = 0
    WINTER_INDEX = 1
    DESERT_INDEX = 2
    ALL_INDEX = 3
    SUMMER = 'summer'
    WINTER = 'winter'
    DESERT = 'desert'
    ALL = 'all'
    SEASONS = [SUMMER, WINTER, DESERT, ALL]
    INDICES = [SUMMER_INDEX, WINTER_INDEX, DESERT_INDEX, ALL_INDEX]